name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write    # needed to create releases/tags
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install release tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine python-semantic-release

      - name: Verify Python environment
        run: |
          python --version
          python -m pip list

      - name: Semantic Release (PyPI + GitHub)
        id: semrel
        uses: python-semantic-release/python-semantic-release@v10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PYPI_USERNAME: __token__                       
          PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}   
          PIP_DISABLE_PIP_VERSION_CHECK: '1'

      # Only build/push Docker if a new release happened
      - name: Log in to Docker Hub
        if: steps.semrel.outputs.released == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker images
        if: steps.semrel.outputs.released == 'true'
        run: |
          VERSION=${{ steps.semrel.outputs.version }}
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/pii-crypto
          docker build -t $IMAGE:$VERSION -t $IMAGE:latest .
          docker push $IMAGE:$VERSION
          docker push $IMAGE:latest